### ISSUE TITLE
Sandbox ui should timeout on sandbox-service crash

### ISSUE THREAD

**Issue by o-orand** [Orange-OpenSource/elpaaso-sandbox-ui#2]
UI waits forever on **sandbox service** failure. It should timeout after some times.

**Comment by gberche-orange** [comment]
Re-opening: reproduces currently on production (experienced by Pascal D): UI hangs on slow sandbox-service response.

Associated sandbox-ui stack trace:

```
2016-01-29T17:53:48.48+0100 [App/0]      OUT 2016-01-29 16:53:47.992  INFO 33 --- [io-61033-exec-2] o.s.c.n.zuul.filters.ProxyRouteLocator   : Finding route for path: /v1/sandboxes/me
2016-01-29T17:54:00.22+0100 [App/0]      OUT 2016-01-29 16:54:00.055  WARN 33 --- [io-61033-exec-2] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering
2016-01-29T17:54:00.22+0100 [App/0]      OUT java.net.SocketTimeoutException: Read timed out
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_60-]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_60-]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_60-]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_60-]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160) ~[httpcore-4.4.4.jar!/:4.4.4]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84) ~[httpcore-4.4.4.jar!/:4.4.4]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273) ~[httpcore-4.4.4.jar!/:4.4.4]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[httpcore-4.4.4.jar!/:4.4.4]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283) ~[httpcore-4.4.4.jar!/:4.4.4]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[httpcore-4.4.4.jar!/:4.4.4]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[httpcore-4.4.4.jar!/:4.4.4]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forwardRequest(SimpleHostRoutingFilter.java:262) ~[spring-cloud-netflix-core-1.1.0.M1.jar!/:1.1.0.M1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forward(SimpleHostRoutingFilter.java:225) ~[spring-cloud-netflix-core-1.1.0.M1.jar!/:1.1.0.M1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:177) ~[spring-cloud-netflix-core-1.1.0.M1.jar!/:1.1.0.M1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112) ~[zuul-core-1.0.28.jar!/:na]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197) ~[zuul-core-1.0.28.jar!/:na]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161) ~[zuul-core-1.0.28.jar!/:na]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:120) ~[zuul-core-1.0.28.jar!/:na]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:84) ~[zuul-core-1.0.28.jar!/:na]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:111) ~[zuul-core-1.0.28.jar!/:na]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:77) ~[zuul-core-1.0.28.jar!/:na]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:158) [spring-webmvc-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequestInternal(ZuulController.java:43) [spring-cloud-netflix-core-1.1.0.M1.jar!/:1.1.0.M1]
2016-01-29T17:54:00.22+0100 [App/0]      OUT    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147) [spring-webmvc-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
```
